version: '3.8'
services:
  database:
    networks:
      - system
    container_name: database
    image: 'petrjahoda/database:latest'
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '10'
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    restart: always
    environment: []
  system_service:
    networks:
      - system
    container_name: system_service
    image: 'petrjahoda/system_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  zapsi_service:
    networks:
      - system
    container_name: zapsi_service
    image: 'petrjahoda/zapsi_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  state_service:
    networks:
      - system
    container_name: state_service
    image: 'petrjahoda/state_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  terminal_service:
    networks:
      - system
    container_name: terminal_service
    image: 'petrjahoda/terminal_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  alarm_service:
    networks:
      - system
    container_name: alarm_service
    image: 'petrjahoda/alarm_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  display_webservice:
    networks:
      - system
    container_name: display_webservice
    image: 'petrjahoda/display_webservice:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
volumes:
  db: null
networks:
  system: null
