version: '3.8'
services:
  database:
    networks:
      - system3
    container_name: database
    image: 'petrjahoda/database:latest'
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '10'
    volumes:
      - 'db:/var/lib/mysql'
      - 'dblogs:/var/log/mysql'
    ports:
      - '5432:5432'
    restart: always
    environment: []
  system_service:
    networks:
      - system3
    container_name: system_service
    image: 'petrjahoda/system_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
#  terminalserver:
#    networks:
#      - zapsi
#    container_name: terminalservercore
#    image: 'petrjahoda/terminalservercore:latest'
#    logging:
#      driver: json-file
#      options:
#        max-size: 5m
#        max-file: '10'
#    depends_on:
#      - zapsidatabase
#    restart: always
#  zapsiserver:
#    networks:
#      - zapsi
#    container_name: zapsiservercore
#    image: 'petrjahoda/zapsiservercore:latest'
#    logging:
#      driver: json-file
#      options:
#        max-size: 5m
#        max-file: '10'
#    depends_on:
#      - zapsidatabase
#    restart: always
#  zapsiweb:
#    networks:
#      - zapsi
#    container_name: zapsiweb
#    image: 'petrjahoda/zapsiweb:latest'
#    logging:
#      driver: json-file
#      options:
#        max-size: 5m
#        max-file: '10'
#    ports:
#      - '80:80'
#    volumes:
#      - 'zapsiweb:/var'
#    restart: always
#  terminalweb:
#    networks:
#      - zapsi
#    container_name: terminalweb
#    image: 'petrjahoda/terminalweb:latest'
#    logging:
#      driver: json-file
#      options:
#        max-size: 5m
#        max-file: '10'
#    ports:
#      - '81:80'
#    volumes:
#      - 'terminalweb:/var'
#    restart: always
volumes:
  db: null
  dblogs: null
#  zapsiweb: null
#  terminalweb: null
networks:
  system3: null
