version: '3.8'
services:
  database:
    networks:
      - system
    container_name: database
    image: 'petrjahoda/database:latest'
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '10'
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    restart: always
    environment: [ ]
  system_service:
    networks:
      - system
    container_name: system_service
    image: 'petrjahoda/system_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  zapsi_demodata_service:
    networks:
      - system
    container_name: zapsi_demodata_service
    image: 'petrjahoda/zapsi_demodata_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  state_service:
    networks:
      - system
    container_name: state_service
    image: 'petrjahoda/state_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  terminal_service:
    networks:
      - system
    container_name: terminal_service
    image: 'petrjahoda/terminal_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  alarm_service:
    networks:
      - system
    container_name: alarm_service
    image: 'petrjahoda/alarm_service:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - database
    restart: always
  display_webservice:
    networks:
      - system
    container_name: display_webservice
    image: 'petrjahoda/display_webservice:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    ports:
      - '81:81'
    depends_on:
      - database
    restart: always
  system_webservice:
    networks:
      - system
    container_name: system_webservice
    image: 'petrjahoda/system_webservice_beta:latest'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    ports:
      - '80:80'
    depends_on:
      - database
    restart: always
  portainer:
    networks:
      - system
    container_name: tools_portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    command: --admin-password '$$2y$05$.sXrFuhMirxUKngp5LVZW.XwKCLQqTtKf.sgfANcu4MDPz5SyzbOq'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  pgadmin:
    container_name: tools_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: petr@jahoda.cz
      PGADMIN_DEFAULT_PASSWORD: pj79..
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - system
    restart: always
  adminer:
    container_name: tools_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - system

volumes:
  portainer_data: null
  db: null
  pgadmin: null

networks:
  system: null